/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void b_min_click1(GButton source, GEvent event) { //_CODE_:b_min:474565:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  sendSteps(0, -10);
} //_CODE_:b_min:474565:

public void b_pl_click2(GButton source, GEvent event) { //_CODE_:b_pl:565569:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  sendSteps(0, 10);
} //_CODE_:b_pl:565569:

public void a_min_click1(GButton source, GEvent event) { //_CODE_:a_min:790633:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  sendSteps(-10, 0);
} //_CODE_:a_min:790633:

public void a_pl_click1(GButton source, GEvent event) { //_CODE_:a_pl:963429:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
  sendSteps(10, 0);
} //_CODE_:a_pl:963429:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  b_min = new GButton(this, 50, 400, 35, 35);
  b_min.setText("B-");
  b_min.addEventHandler(this, "b_min_click1");
  b_pl = new GButton(this, 120, 400, 35, 35);
  b_pl.setText("B+");
  b_pl.addEventHandler(this, "b_pl_click2");
  a_min = new GButton(this, 50, 340, 35, 35);
  a_min.setText("A-");
  a_min.addEventHandler(this, "a_min_click1");
  a_pl = new GButton(this, 120, 340, 35, 35);
  a_pl.setText("A+");
  a_pl.addEventHandler(this, "a_pl_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton b_min; 
GButton b_pl; 
GButton a_min; 
GButton a_pl; 
